##############################################################################################################
# 
# 
#       Program to create the soils File in PIHM from Data in SSurgo and other resources
#       
#    
# 
#       For MM_PHIM input format corresponding to  (Prerelease 0.6.0 Alpha git@github.com:PSUmodeling/MM-PIHM.git)
# 
# 
#  Felipe Montes 2015 /11 /13
#  Revised       2017 /09 /29
# 
# 
# 
############################################################################################################### 



###############################################################################################################
#                             Tell the program where the package libraries are stored                        
###############################################################################################################


#  Tell the program where the package libraries are  #####################

.libPaths("C:/Felipe/SotwareANDCoding/R_Library/library")  ;


###############################################################################################################
#                             Setting up working directory                        
###############################################################################################################


#      set the working directory


setwd('C:\\Felipe\\PIHM-CYCLES\\PIHM\\PIHM SIMULATIONS\\YAHARA\\MM_PHIM_inputs') ;       #  setwd(RevisedOutputs.dir)   ;



###############################################################################################################
#                            Install the packages that are needed                       
###############################################################################################################


# Install the packages that are needed #

# install.packages('ggplot2', dep=TRUE)
# install.packages('base64enc' , dep=TRUE)
# install.packages("raster", dep = TRUE)
# install.packages('plyr', dep=TRUE)
# install.packages('Hmisc', dep=TRUE)
# install.packages('soilDB', dep=TRUE) # stable version from CRAN + dependencies
# install.packages("soilDB", repos="http://R-Forge.R-project.org") # most recent copy from r-forge
# install.packages("SSOAP", repos = "http://www.omegahat.org/R", type="source") # SSOAP and XMLSchema




# install.packages("foreign")
# install.packages("httr", dep=TRUE)
# install.packages("rgdal", dep = TRUE)

# install.packages("rgeos", dep = TRUE)
# install.packages("RColorBrewer")
# install.packages("latticeExtra")
# install.packages("reshape")
# install.packages("dplyr", dep=TRUE)
# install.packages("aqp", dep=TRUE)





###############################################################################################################
#                           load the libraries that are neded   
###############################################################################################################


# load libraries
library(Hmisc) ;
library(plyr) ;
library(dplyr)  ;
library(soilDB) ;
library(raster) ;
library(aqp) ;
library(sp) ;
library(rgdal) ; 
library(rgeos) ; 
library(lattice) ;
library(MASS) ;
library(RColorBrewer) ;
library(ggplot2)  ;
#library(tmap) ;
library(tidyr)  ;
library(devtools) ;
library(stats)
library(DescTools);



# ########################## import the raster file with the GSSURGO Data for the watershed in PIHM ####################
# 
# 
# Manhatango_GSSURGO<- raster('C:\\Felipe\\PIHM-CYCLES\\PIHM\\PIHM_Felipe\\CNS\\Manhantango\\gssurgo_g_pa\\GSSURGO_PA_TIFF\\MahatangoGSSG1.tif') ;
# 
# # generate a RAT via raster package functionality
# Manhatango_GSSURGO <- ratify(Manhatango_GSSURGO) ;
# 
# # extract RAT to a data.frame
# MUKEYS <- levels(Manhatango_GSSURGO)[[1]] ;
# 
# ##### The File above contains all the mukeys in the GSSURGO raster data enclosed by the Mahatango wateshed boundaries. This 
# ##### includes all Map units in the map. In order to better select soil properties for PIHM smiulations, the mesh file generated by PIHM-GIS is supper inposed on the GGSURGO data and from each trinagle the best representation of soil mapunits is extracted and from that the soil infomration required by PIHM. PIHM-GIS extracts centroid information, that is the mapunit that is located at the centroid of each trinagle. This is done for easiness and clarity. 
# ##### In this program we wil extract the map unit that is most frequent  (mode) in each trinagle based on GSSURGO raster pixel counts. This is expected to be more representative of the watershed conditions. To do that , the Zonal Statistics raster tool in GIS is used and the statistical mode for each triangle is selected.
# 
###########################################################################################################################






#### import the shape files from QGIS with the MUKEY mode from each triangle ####

########### Read infromation about the shape files ###########

# HansYoust.mesh.info<-ogrInfo("C:/Felipe/PIHM-CYCLES/PIHM/PIHM_Felipe/CNS/Manhantango/HydroTerreFullManhantango/HansYostDeepCreek/GSSURGO/HY_GSURGO.shp");

Project.mesh.info<-ogrInfo("../Oct0920191330/DomainDecomposition/MergeFeatures_q30_a1000000_o.shp")  ; 

#### read the shape file that has been created in QGIS using the zonal statistics

# HansYoust.GSSURGO<-readOGR("C:/Felipe/PIHM-CYCLES/PIHM/PIHM_Felipe/CNS/Manhantango/HydroTerreFullManhantango/HansYostDeepCreek/GSSURGO/HY_GSURGO.shp")  ;

Project.GSSURGO<-readOGR("../Oct0920191330/DomainDecomposition/MergeFeatures_q30_a1000000_o.shp" )  ;  

head(Project.GSSURGO@data)


# str(HansYoust.GSSURGO) ;

str(Project.GSSURGO, max.level = 2) ;


#plot(HansYoust.GSSURGO);

plot(Project.GSSURGO) ;


#str(HansYoust.GSSURGO@data) ;

str(Project.GSSURGO@data)  ; 

#### Extract the Mukeys corresponding to the mode in each mesh triangle


# HansYoust.GSSURGO@data$MUKEYS.mode<-as.factor(HansYoust.GSSURGO@data$SSURGO_mod) ;

Project.GSSURGO@data$MUKEYS.mode<-as.factor(Project.GSSURGO@data$GSURGO_Mod) ;


#MUKEYS<-levels(HansYoust.GSSURGO@data$MUKEYS.mode)  ;

MUKEYS<-levels(Project.GSSURGO@data$MUKEYS.mode)  ;

str(MUKEYS)  ;


################################ Query the Soil Data access database with SQL through R #################


# from https://sdmdataaccess.sc.egov.usda.gov/queryhelp.aspx
# and https://sdmdataaccess.sc.egov.usda.gov/documents/ReturningSoilTextureRelatedAttributes.pdf


# --Sample query begins.
# --Note that a pair of dashes denotes the beginning of a comment. 
# SELECT
# saversion, saverest, -- attributes from table "sacatalog"
# l.areasymbol, l.areaname, l.lkey, -- attributes from table "legend"
# musym, muname, museq, mu.mukey, -- attributes from table "mapunit"
# comppct_r, compname, localphase, slope_r, c.cokey, -- attributes from table "component"
# hzdept_r, hzdepb_r, ch.chkey, -- attributes from table "chorizon"
# sandtotal_r, silttotal_r, claytotal_r, --total sand, silt and clay fractions from table "chorizon"
# sandvc_r, sandco_r, sandmed_r, sandfine_r, sandvf_r,--sand sub-fractions from table "chorizon"
# texdesc, texture, stratextsflag, chtgrp.rvindicator, -- attributes from table "chtexturegrp"
# texcl, lieutex, -- attributes from table "chtexture"
# texmod -- attributes from table "chtexturemod"
# FROM sacatalog sac
# INNER JOIN legend l ON l.areasymbol = sac.areasymbol AND l.areatypename = 'Non-MLRA Soil Survey Area'
# INNER JOIN mapunit mu ON mu.lkey = l.lkey
# AND mu.mukey IN
# ('107559','107646','107674','107682','107707','107794','107853','107854','107865','107867','107869','107870','107871')
# LEFT OUTER JOIN component c ON c.mukey = mu.mukey
# LEFT OUTER JOIN chorizon ch ON ch.cokey = c.cokey
# LEFT OUTER JOIN chtexturegrp chtgrp ON chtgrp.chkey = ch.chkey
# LEFT OUTER JOIN chtexture cht ON cht.chtgkey = chtgrp.chtgkey
# LEFT OUTER JOIN chtexturemod chtmod ON chtmod.chtkey = cht.chtkey
# --WHERE.
# --ORDER BY l.areaname, museq, comppct_r DESC, compname, hzdept_r -- standard soil report ordering
# --Sample query ends. 

# extract the map unit keys from the RAT, and format for use in an SQL IN-statement
#in.statement2 <- format_SQL_in_statement(MUKEYS$ID); 

in.statement2 <- format_SQL_in_statement(MUKEYS); 

# The above is teh same as the two instructions below combined 
# Temp_1 <- paste(MUKEYS, collapse="','") ;
# Temp_2<- paste("('", Temp_1 , "')", sep='') ;



# format query in SQL- raw data are returned

Pedon.query<- paste0("SELECT component.mukey, component.cokey, compname, comppct_r, majcompflag, slope_r, hzdept_r, hzdepb_r,hzthk_r, hzname, awc_r, sandtotal_r, silttotal_r, claytotal_r, om_r,dbtenthbar_r, dbthirdbar_r, dbfifteenbar_r, fraggt10_r, frag3to10_r, sieveno10_r, sieveno40_r, sieveno200_r, ksat_r  FROM component JOIN chorizon ON component.cokey = chorizon.cokey AND mukey IN ", in.statement2," ORDER BY mukey, comppct_r DESC, hzdept_r ASC") ;

# now get component and horizon-level data for these map unit keys
Pedon.info<- SDA_query(Pedon.query);
head(Pedon.info) ;
str(Pedon.info)  ;


########################################## IMPORTANT ###########################################################

### Map Unit No. 539762 is a water body and is not available to query from the SDA_query function

### Map Unit No. 539759 are urban land Urban land-Udults complex

### Map Unit No. 542030, 542033, 542034 Opequon  https://casoilresource.lawr.ucdavis.edu/sde/?series=opequon
                 # some layers do not have data
 
### Map Unit No. 542034 Pits  https://casoilresource.lawr.ucdavis.edu/soil_web/ssurgo.php?action=explain_mapunit&mukey=542034

### Map Unit No.  927072 Quarries

### Map Unit No. 542043  https://casoilresource.lawr.ucdavis.edu/sde/?series=vanderlip


### Map Unit No.753522 Houghton Muck Peatlands with no reliable data

# https://nasis.sc.egov.usda.gov/NasisReportsWebSite/limsreport.aspx?report_name=Pedon+Description+html+(userpedid)&pedon_id=74WI025001
# https://ncsslabdatamart.sc.egov.usda.gov/rptExecute.aspx?p=1603&r=1&submit1=Get+Report
# https://ncsslabdatamart.sc.egov.usda.gov/rptExecute.aspx?p=1603&r=1&submit1=Get+Report



### Map Unit No. 423299 Marsh Peatlands with no reliable data


### Map Unit No.753456 Alluvial Wet Peatlands with no reliable data 

### ### Map Unit No. 753597 and 700421  Water 

###############################################################################################################

Pedon.info[Pedon.info$mukey==539762,]

Pedon.info[Pedon.info$mukey==539759,]

Pedon.info[Pedon.info$mukey==542030,]

Pedon.info[Pedon.info$mukey==542033,]

Pedon.info[Pedon.info$mukey==542034,]

Pedon.info[Pedon.info$mukey==542043,]

Pedon.info[Pedon.info$mukey==753522,]

Pedon.info[Pedon.info$mukey==423299,]


Pedon.info[Pedon.info$mukey==753456,]

Pedon.info[Pedon.info$mukey==753597,]

Pedon.info[Pedon.info$mukey==700421,]



# filter components that are the major components of each unit map with the Flag majcompflag=='Yes'

Pedon.info.MajorC<-Pedon.info[which(Pedon.info$majcompflag == 'Yes'),]  ;
head(Pedon.info.MajorC) ; 
str(Pedon.info.MajorC)  ;



# check if there are mukeys with more than one dominant component

Pedon.info.MajorC$mukey.factor<-as.factor(Pedon.info.MajorC$mukey) ;

str(Pedon.info.MajorC$mukey.factor)


Pedon.info.MajorC$mukey_comppct_r<-paste(Pedon.info.MajorC$mukey.factor,Pedon.info.MajorC$comppct_r, sep = "_") ;

# Select major component mukeys that have also the highest component percent comppct_r

head(Pedon.info.MajorC)  ;

Dominant<- aggregate(comppct_r ~ mukey.factor, data=Pedon.info.MajorC, FUN="max" , drop=T, simplify=T) ;

head(Dominant)  ;

str(Dominant) ;

Dominant$mukey_comppct_r<-paste(Dominant$mukey.factor,Dominant$comppct_r, sep ="_");


Mukey.Pedon<-Pedon.info.MajorC[Pedon.info.MajorC$mukey_comppct_r %in% Dominant$mukey_comppct_r,]  ;

str(Mukey.Pedon) ;


# Creating Mukey ID for each dominant component


Mukey.Pedon$mukey_ID<-as.character(Mukey.Pedon$mukey) ;


str(Mukey.Pedon);


#  Transform the Pedon.info query in to the right format to be converted into a SoilProfileCollection object
#   https://ncss-tech.github.io/AQP/aqp/aqp-intro.html


#Pedon.info$id<-Pedon.info$mukey ;
# Pedon.info$top<-Pedon.info$hzdept_r ;
# Pedon.info$bottom<-Pedon.info$hzdept_r ;
#Pedon.info$name<-Pedon.info$hzname ;

depths(Mukey.Pedon)<-mukey_ID ~ hzdept_r + hzdepb_r  ;
str(Mukey.Pedon) ;


plot(Mukey.Pedon, name='hzname',color='dbthirdbar_r')  ;


# Add soil profile depth  soil.depth

Mukey.Pedon$soil.depth<-profileApply(Mukey.Pedon, FUN=max) ; 

# Using the functions  profileApply and estimateSoilDepth  from the package Algorithms for Quantitative Pedology 
# https://cran.r-project.org/web/packages/aqp/aqp.pdf 


Mukey.Pedon$soil.depth2<-profileApply(Mukey.Pedon, estimateSoilDepth, name="hzname", top="hzdept_r",bottom="hzdepb_r" ) ; 

Mukey.Pedon$hzthickns_r<-Mukey.Pedon$hzdepb_r-Mukey.Pedon$hzdept_r  ;

str(Mukey.Pedon) ;

# add total soil depth to each horizon

Mukey.Pedon@horizons<-merge(Mukey.Pedon@horizons, Mukey.Pedon@site, by.x='mukey', by.y='mukey_ID') ;

Mukey_Pedon_info<-Mukey.Pedon@horizons ;


str(Mukey.Pedon) ;



######### Use the slice tool to divide the horizons into 1 cm layers and sum the components (clay, sand, silt) multiplied by 
#########  the thincknes (1cm) and the bulk density dbthirdbar_r to obtain the wieghted clay, sand, etc for pihm


sliced<-aqp::slice(Mukey.Pedon, fm = 1:max(Mukey.Pedon) ~ sandtotal_r + silttotal_r + claytotal_r + om_r + dbthirdbar_r  + soil.depth + mukey.factor ) ;




plot(sliced, name='hzname', color='om_r') ;

str(sliced) ;



# sliced2<-aqp::slice(Mukey.Pedon[1:10], fm = seq(0,max(Mukey.Pedon),by=10) ~ sandtotal_r + silttotal_r + claytotal_r + om_r + dbthirdbar_r) ;
# 
# sliced2@horizons$hzdepb_r<-sliced2@horizons$hzdept_r+10





######   multiply the thincknes (1 cm) and the bulk density dbthirdbar_r to the component percentage to obtain the weighted component

##### sum the weighted component 1 cm layers  to obtained the weighted average component


sliced@site$SOIL_MASS<- profileApply(sliced, FUN=function(x) sum(x$dbthirdbar_r, na.rm=T), simplify = T) ;


sliced@site$SANDMASS<- profileApply(sliced, FUN=function(x) sum((x$sandtotal_r*x$dbthirdbar_r)/100, na.rm=T), simplify = T) ;

sliced@site$SILTMASS<- profileApply(sliced, FUN=function(x) sum((x$silttotal_r*x$dbthirdbar_r)/100, na.rm=T), simplify = T) ;

sliced@site$CLAYMASS<- profileApply(sliced, FUN=function(x) sum((x$claytotal_r*x$dbthirdbar_r)/100, na.rm=T), simplify = T) ;

sliced@site$OM_MASS<- profileApply(sliced, FUN=function(x) sum((x$om_r*x$dbthirdbar_r)/100, na.rm=T), simplify = T) ;


sliced@site$SAND<-(sliced@site$SANDMASS/sliced@site$SOIL_MAS)*100   ;

sliced@site$SILT<-(sliced@site$SILTMASS/sliced@site$SOIL_MAS)*100   ;

sliced@site$CLAY<-(sliced@site$CLAYMASS/sliced@site$SOIL_MAS)*100   ;

sliced@site$TEXTURE_CHECK<-sliced@site$SAND + sliced@site$SILT + sliced@site$CLAY ;


sliced@site$OM<- (sliced@site$OM_MASS/sliced@site$SOIL_MAS)*100   ;

sliced@site$BULKD<-sliced@site$SOIL_MASS/sliced@site$soil.depth ;



head(sliced@site)




####### write the soils data in a format that PIHM can read trough the Data model Loader step in PIHM-GIS
####### include an index to replace the MUKEY with the indexs, as PIHM does not read the MUKEYS and needs an integer index instead
sliced@site$mukey_No<-as.numeric(sliced@site$mukey_ID)

str(sliced@site)

str(Project.GSSURGO@data)


MUKEYS.INDX<-data.frame(sliced@site[order(sliced@site$mukey_No),c('mukey_No','mukey_ID')],seq(1:length(sliced@site$mukey_No))) ;
names(MUKEYS.INDX)<-c('mukey_No',"mukey_ID","mukey_Index" ) ;
  
str(MUKEYS.INDX)


MUKEYS.MAP<-merge(Project.GSSURGO@data,MUKEYS.INDX, by.x="GSURGO_Mod", by.y="mukey_No", all.x=T )

str(MUKEYS.MAP)

### combine the information and prepare it to create the .soil file

# HansYoust_Soil<-merge(sliced@site[, c("mukey_ID", "SILT", "CLAY" , "OM" , "BULKD")], MUKEYS.map.2, by.x='mukey_ID', by.y='MUKEYS', all=T) ;

Project_Soil<-merge(sliced@site[, c("mukey_No", "mukey_ID", "SILT", "CLAY" , "OM" , "BULKD")], MUKEYS.INDX, by=c('mukey_No', 'mukey_ID') , all=T) ;

### order the dataframe by the mukey_Index 

Project_Soil<-Project_Soil[order(Project_Soil$mukey_Index),]

# HansYoust_Soil[,c("SILT", "CLAY" , "OM" , "BULKD")]<-signif(HansYoust_Soil[,c("SILT", "CLAY" , "OM" , "BULKD")], digits=4)

Project_Soil[,c("SILT", "CLAY" , "OM" , "BULKD")]<-signif(Project_Soil[,c("SILT", "CLAY" , "OM" , "BULKD")], digits=4) ;

# names(HansYoust_Soil)<-c('MUKEY','SILT',  'CLAY',	'OM',	'BD', 'INDEX'); 

names(Project_Soil)<-c('MUKEY','SILT',  'CLAY',	'OM',	'BD', 'INDEX') ;

str(Project_Soil) ;

head(Project_Soil) ;


##### Adding the additional columns for the new PIHM-MM module inputs

# HansYoust_Soil$KINF<-HansYoust_Soil$KSATV<-HansYoust_Soil$KSATH<-HansYoust_Soil$MAXSMC<-HansYoust_Soil$MINSMC<-HansYoust_Soil$ALPHA<-HansYoust_Soil$BETA<-HansYoust_Soil$MACHF<-HansYoust_Soil$MACVF<-HansYoust_Soil$DMAC<-HansYoust_Soil$QTZ<- -999 ;

Project_Soil$KINF<-Project_Soil$KSATV<-Project_Soil$KSATH<-Project_Soil$MAXSMC<-Project_Soil$MINSMC<-Project_Soil$ALPHA<-Project_Soil$BETA<-Project_Soil$MACHF<-Project_Soil$MACVF<-Project_Soil$DMAC<-Project_Soil$QTZ<- -999 ;



# ###########################################################################################################################
# 
# ###     Prepare the Geology data for PIHM based on the properties of the depest layer of the horizon
# ###     of the dominant components of each map unit selected by the procedure used for soils data
# 
# ###########################################################################################################################


Neeed to compare the dominant selected components of the Geology file with the ones selected for the soil files. There seesm to be some differences.


Mukey.deepest<-Mukey.Pedon@horizons[Mukey.Pedon@horizons$hzdepb_r == Mukey.Pedon@horizons$soil.depth,]  ;



str(Mukey.deepest) ;



# HansYoust_deepest<-Mukey.deepest [, c("mukey_ID", "silttotal_r", "claytotal_r" , "om_r" , "dbthirdbar_r")] ;

Project_deepest<-Mukey.deepest [, c("mukey_ID", "silttotal_r", "claytotal_r" , "om_r" , "dbthirdbar_r")] ;



# names(HansYoust_deepest)<-c('MUKEY','SILT',  'CLAY',	'OM',	'BD'); 

names(Project_deepest)<-c('MUKEY','SILT',  'CLAY',	'OM',	'BD'); 






###  Select the mukeys that have variables with NA values

Mukey.deepest.NA<-Project_deepest[which(is.na(Project_deepest),arr.ind=T)[,1],'MUKEY'] ;




Mukey.deepest.1<-Mukey.Pedon@horizons[Mukey.Pedon@horizons$mukey_ID %in% Mukey.deepest.NA, ]; 


Mukey.deepest.1.deepest<-Mukey.deepest.1[Mukey.deepest.1$hzdepb_r == Mukey.deepest.1$soil.depth,] ;


###    Some horizons do not have complete data for the deepest layer. Therefore the next step is to
### take the data from the layer inmediately above the deepest 


### Select the mukeys in that have one horizon above the deepest horizon . This is done by checking if the mukey of the row above the depst horizon is still the same mukey 

Mukey.deepest.1.deepest.above<-Mukey.Pedon@horizons[as.integer(row.names(Mukey.deepest.1.deepest))-1,] ;




No.above.horizon<-Mukey.deepest.1.deepest[which(Mukey.deepest.1.deepest$mukey != Mukey.deepest.1.deepest.above$mukey),];

### The No.above.horizon mukeys "423299, Marsh" , "753456 Alluvial land, wet" and "1588007, Pits", do not have horizons above from where to take the data for the geology file

No.above.horizon.info<-Mukey.Pedon@horizons[as.integer(row.names(No.above.horizon)),c("mukey_ID", "silttotal_r", "claytotal_r" , "om_r" , "dbthirdbar_r")] ;



Mukey.deepest.2<-Mukey.deepest.1.deepest[!Mukey.deepest.1.deepest$mukey %in% No.above.horizon$mukey, ] ;


Mukey.deepest.2.info<-Mukey.Pedon@horizons[as.integer(row.names(Mukey.deepest.2))-1,c("mukey_ID", "silttotal_r", "claytotal_r" , "om_r" , "dbthirdbar_r")]

names(Mukey.deepest.2.info)<-c('MUKEY','SILT',  'CLAY',	'OM',	'BD');





### mukey 542034 is abandoned mine pitts, this have no data at all, The data will be replaced by the average of the data available for # the neighboring triangles in each case. Therefore triangles with soil index 57 (542034) will not be used and tringles with new indeces # created with the average values from neighbouring trinagles will be used. In order to not create warnings when procesing the soil file, soil indices with no data will be filled with Standard data.


#### The standarized arbitrary values are silt=0.33, clay=0.33. OM=0.5, BD= 1.5

#Mukey.deepest.2.No.above.horizon[,c('SILT',  'CLAY',	'OM',	'BD')]<-StandardSoilValues ;

###  Adding statndard soil values to the No.above.horizon.info mukeys 


No.above.horizon.info[c("silttotal_r", "claytotal_r" , "om_r" , "dbthirdbar_r")]<-c(0.33, 0.33 , 0.5 , 1.5 );

names(No.above.horizon.info)<-c('MUKEY','SILT',  'CLAY',	'OM',	'BD');

### Collecting all the information together


Mukey.deepest.3<-rbind(Mukey.deepest.2.info,No.above.horizon.info) ;




Project_deepest[Project_deepest$MUKEY %in% Mukey.deepest.NA, ]<-Mukey.deepest.3  ;


Project_deepest[, c('SILT',  'CLAY',	'OM',	'BD')] <-signif(Project_deepest[, c('SILT',  'CLAY',	'OM',	'BD')], digits=4) ;

####### write the geology data in a format that PIHM can read trough the Data model Loader step in PIHM-GIS
####### include an index to replace the MUKEY with the index, as PIHM does not read the MUKEYS and needs an integer index instead


# HansYoust_Geology<-merge(HansYoust_deepest, MUKEYS.map.2, by.x='MUKEY', by.y='MUKEYS', all=T) ;

Project_Geology<-merge(Project_deepest, MUKEYS.map.2, by.x='MUKEY', by.y='MUKEYS', all=T) ;


# names(HansYoust_Geology)<-c('MUKEY','SILT',  'CLAY',	'OM',	'BD', 'INDEX'); 

names(Project_Geology)<-c('MUKEY','SILT',  'CLAY',	'OM',	'BD', 'INDEX'); 

str(Project_Geology) ;

head(Project_Geology)  ;

# NUMGEOL<-data.frame(c('NUMGEOL'), dim(HansYoust_Geology)[1]) ;

NUMGEOL<-data.frame(c('NUMGEOL'), dim(Project_Geology)[1]) ;

##### Adding the additional columns for the new PIHM-MM module inputs

# HansYoust_Geology$KINF<-HansYoust_Geology$KSATV<-HansYoust_Geology$KSATH<-HansYoust_Geology$MAXSMC<-HansYoust_Geology$MINSMC<-HansYoust_Geology$ALPHA<-HansYoust_Geology$BETA<-HansYoust_Geology$MACHF<-HansYoust_Geology$MACVF<-HansYoust_Geology$DMAC<-HansYoust_Geology$QTZ<- -999 ;

Project_Geology$KINF<-Project_Geology$KSATV<-Project_Geology$KSATH<-Project_Geology$MAXSMC<-Project_Geology$MINSMC<-Project_Geology$ALPHA<-Project_Geology$BETA<-Project_Geology$MACHF<-Project_Geology$MACVF<-Project_Geology$DMAC<-Project_Geology$QTZ<- -999 ;



# #############################################################################################################################
# #
# #
# ####################### Write the soil and geology data in the format approptiate for PIHM to take #############################
# 
# # NUMSOIL<-data.frame(c('NUMSOIL'), dim(HansYoust_Soil)[1]) ;
# 
# NUMSOIL<-data.frame(c('NUMSOIL'), dim(Project_Soil)[1]) ;
# 
# 
# # NUMGEOL<-data.frame(c('NUMGEOL'), dim(HansYoust_Geology)[1]) ;
# 
# NUMGEOL<-data.frame(c('NUMGEOL'), dim(Project_Geology)[1]) ;
# 
# 
# write.table(NUMSOIL,file=paste0(inputfile.name, '_Soil.txt'), row.names=F , quote=F, sep = "\t", col.names=F) ;
# 
# # write.table(HansYoust_Soil[, c('INDEX','SILT',  'CLAY',	'OM','BD', 'KINF', 'KSATV' , 'KSATH' , 'MAXSMC' , 'MINSMC' , 'ALPHA' , 'BETA' , 'MACHF' , 'MACVF' , 'DMAC', 'QTZ')],file=paste0(inputfile.name, '_Soil.txt'), row.names=F , quote=F, sep = "\t", append= T) ;
# 
# write.table(Project_Soil[, c('INDEX','SILT',  'CLAY',	'OM','BD', 'KINF', 'KSATV' , 'KSATH' , 'MAXSMC' , 'MINSMC' , 'ALPHA' , 'BETA' , 'MACHF' , 'MACVF' , 'DMAC', 'QTZ')],file=paste0(inputfile.name, '_Soil.txt'), row.names=F , quote=F, sep = "\t", append= T) ;
# 
# ####################  Add DINF , KMACV_RO  and KMACH_RO  at the end of the soil file ################
# # DINF (type: double, unit: m) A virtual top soil layer thickness across which infiltration is calculated.
# # KMACV RO (type: double, unit: dimensionless) Ratio between vertical macropore hydraulic conduc-
# #   tivity and vertical saturated infiltration hydraulic conductivity.
# # KMACH RO (type: double, unit: dimensionless) Ratio between horizontal macropore hydraulic con-
# #   ductivity and horizontal saturated hydraulic conductivity.
# 
# DINF_etc<-data.frame(c('DINF' , 'KMACV_RO', 'KMACH_RO'), c( 0.10, 100.0 , 1000.0 )) ;
# 
# write.table(DINF_etc,file=paste0(inputfile.name, '_Soil.txt'), row.names=F , col.names=F ,quote=F, sep = "\t", append= T) ;
# 
# 
# # NUMGEOL<-data.frame(c('NUMGEOL'), dim(HansYoust_Geology)[1]) ;
# 
# NUMGEOL<-data.frame(c('NUMGEOL'), dim(Project_Geology)[1]) ;
# 
# 
# # write.table(HansYoust_Geology[, c('INDEX','SILT',  'CLAY',	'OM','BD', 'KINF', 'KSATV' , 'KSATH' , 'MAXSMC' , 'MINSMC' , 'ALPHA' , 'BETA' , 'MACHF' , 'MACVF' , 'DMAC', 'QTZ')],file=paste0(inputfile.name, '_Geology.txt'), row.names=F , quote=F, sep = "\t", append= T) ;
# 
# write.table(Project_Geology[, c('INDEX','SILT',  'CLAY',	'OM','BD', 'KINF', 'KSATV' , 'KSATH' , 'MAXSMC' , 'MINSMC' , 'ALPHA' , 'BETA' , 'MACHF' , 'MACVF' , 'DMAC', 'QTZ')],file=paste0(inputfile.name, '_Geology.txt'), row.names=F , quote=F, sep = "\t", append= T) ;
# 
# 
# write.table(DINF_etc, file=paste0(inputfile.name, '_Geology.txt'), row.names=F , quote=F, sep = "\t", col.names=F, append= T ) ;
# 




# 
# ####################### done for now #################################################################################

######## Create the directory where the objects created in the file PIHMInputsR.RData are to be saved

#dir.create(paste0('C:\\Felipe\\PIHM-CYCLES\\PIHM\\PIHM_R_Scripts\\MM_PIHM_inputs\\',Project));

save.image(file='SoilsSurgoPIHM.RData');










